### ISSUE TITLE
Phase and period

### ISSUE THREAD

**Issue by estebanbeck** [rethomics/rethomics.github.io#4]
The idea of this is to shift the data in order to, instead of starting the plot at ZT00, for instance, start at ZT18.

This implementation:

```
stat_ld_annotations(phase = hours(1))
```

only changes the annotation (the light and dark bar plots), but it doesn't move the data accordingly.

**Comment by qgeissmann** [comment]
This is on purpose, `stat_ld_annotation` is just a layer, so it should not (cannot) change the other layers.
However, I will work on the `time_offset` argument  in `ggetho` (see https://github.com/rethomics/ggetho/issues/12).

**Comment by qgeissmann** [comment]
please follow rethomics/ggetho#12 for updates. closing this duplicate.
